version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel-app
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"  
    networks:
      - laravel-micro-repo

  web:
    image: nginx:latest
    container_name: laravel-nginx
    ports:
      - "8081:80"  
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel-micro-repo

  db:
    image: mysql:8.0
    container_name: laravel-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: laravel
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"  
    networks:
      - laravel-micro-repo

  node:
    image: node:18
    container_name: laravel-node
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: sh -c "npm install && npm run dev"
    networks:
      - laravel-micro-repo

volumes:
  db-data:

networks:
  laravel-micro-repo:
